### ISSUE TITLE
A little example, please

### ISSUE THREAD

**Issue by felmur** [simonowen/resid#3]
Hello,

I decided to write this post after trying to figure out how to implement this library in my c64 emulator for months.
My difficulty is how to get a sound by writing its values into the SID registers. Currently, writing values to registers does not appear to generate any sound.
The poor documentation of the library doesn't help in the slightest.
Could you have a little C ++ example showing how to get a sound by writing to the SID registers?
It could also be included in the distribution of the library, facilitating the work of those who want to use it.
Thank you and greetings.

**Comment by simonowen** [comment]
The project here is just a simple CMake build wrapper around the original project source code, so there hasn't really been any attempt to enhance it.  The only documentation that exists is what the original authors wrote.

That said, I have used the library in my own emulation project so I'm familiar with using it.

The reSID library exposes a C++ object so it expects the part of your project that includes it will be C++ too.  You need to include the main library header, declare an object of that type, then initialise it:

```c++
#include "sid.h"

SID sid;
sid.set_chip_model(MOS6581);
sid.reset();
sid.adjust_sampling_frequency(44100);
```

That configures it as an original 6581 SID chip model, resets the chip state, and tells it you want it to generate sound samples at a rate of 44.1KHz.  The library doesn't output any sound directly, instead providing the sample data for you to play it. You'll need to open a sound device and configure a setup to seamlessly stream sound data into it for playback.

During your C64 emulation you'll have writes to the SID chip under addresses &D4xx.  You should write these into the SID chip emulation using:

```c++
sid.write(reg & 0x1f, val);
```
_reg_ is the 8-bit address offset, which is masked to a 5-bit SID register, and _val_ is the 8-bit value written to that location.

At the end of each frame (and ideally just before each register write) you'll want to ask the SID emulation for sound samples from the current chip state using:

```c++
sid.clock(SID_CLOCK_PAL, sample_buffer, num_samples, 1);
```

_sample_buffer_ should be a pointer to a buffer of short values (16-bit signed samples) to receive the sample data.  _num_samples_ is the number of samples you want to generate, which will depend on how much time has elapsed since the last time you called `sid.clock()`.  At 44.1KHz you're generating 44100 samples per second, which is 882 samples per 50Hz PAL frame.  Queue up the new samples for playback and continue your emulation.

Note that the sound samples the library generates are mono.  If you have a sound device expecting a stereo buffer, change the final parameter from 1 to 2.  This causes it to generate data for the left channel only and skip over the data for the right channel.  Then you can add a small loop to copy the left samples to the right interleaved half of the buffer.

If you're building under Windows there is an extra complication. The main SID emulation class is called `SID`, which can conflict with the `SID` (security identifier) type from the Windows headers.  I had to temporarily redefine the _SID_ symbol using the pre-processor to avoid the clash, using something like:

```c++
#define SID WIN32_SID
#include <windows.h>
#undef SID
#include "sid.h"
```

It's not pretty but it does work around the issue.  Hopefully that should be enough to get you up and running.

**Comment by felmur** [comment]
Hello Simon, thank you for your fast reply.

Thanks also for your suggestions, now I'm trying to get a sound by writing in the SID registers writing a c++ source under Archlinux.

Since I didn't find any reference to the value of SID_CLOCK_PAL, I set it to the C64 clock value:

cycle_count SID_CLOCK_PAL = 985248;

It's correct?

**Comment by felmur** [comment]
OK, now I have a simple program, residtest, which works as expected.
If anyone is interested, this is the repository:
https://github.com/felmur/residtest.git

Thank you for all, Simon.

**Comment by simonowen** [comment]
You're right about the `SID_CLOCK_PAL` definition, which I thought it was part of the reSID library but is something I'd defined in my own use case.

Glad to hear you have it working now, and thanks for posting a simple example project using it.  :)
